---
substitutions:
  id_prefix: ratgdov2
  friendly_name: "RATGDOv2"
  uart_tx_pin: 22
  uart_rx_pin: 23
  input_obst_pin: 20
  status_door_pin: 19
  status_obstruction_pin: 18
  dry_contact_open_pin: 17
  dry_contact_close_pin: 16
  dry_contact_light_pin: 15

web_server:

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ratgdo.esphome
    version: "2.0"

esp32:
  board: esp32dev

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v2board_esp32_d1_mini.yaml@main

packages:
  - !include base.yaml
  # remote_package:
    # path: .
    # files: [base.yaml]
    # url: https://github.com/ratgdo/esphome-ratgdo
    # files: [base.yaml]
    # refresh: 1s

switch:
  - platform: gpio
    id: relay_1
    pin: GPIO13
    name: "Outdoor Lights"
  - platform: gpio
    id: relay_2
    pin: GPIO12
    name: "Indoor Lights"

binary_sensor:
  - platform: gpio
    id: switch_1
    pin: GPIO26
    internal: true
    filters:
      delayed_on_off: 50ms
    on_state:
     - switch.toggle: relay_1

  - platform: gpio
    id: switch_2
    pin: GPIO27
    internal: true
    filters:
      delayed_on_off: 50ms
    on_state:
     - switch.toggle: relay_2

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

improv_serial:

wifi:
  ssid: Clarkinello
  password: TallTree4175

logger:
  level: DEBUG
